### ISSUE TITLE
Enable Netlify on software-project-blueprint repository

### ISSUE THREAD

**Issue by mcleo-d** [finos/software-project-blueprint#27]
## Description

`Netlify` should be integrated into the `software-project-blueprint` repository to enable `Docusaurus` builds and previewing upon pull request. The following tasks should be followed.

### Tasks
- [x] Remove GitHub Action https://github.com/finos/software-project-blueprint/blob/main/.github/workflows/docusaurus.yml
- [x] Enable `Netlify` on `software-project-blueprint`
- [x] Test against pull request #26

**Comment by maoo** [comment]
all done!
